title: The Social Network Inbox
description: "All About The Social Network(David Fincher Film) / Chinese Translation"
author:
  name: "homepage"
  email: "thesocialnetworkinbox@protonmail.com"
  url: "https://thesocialnetworkinbox.github.io/"

baseurl: https://thesocialnetworkinbox.github.io/

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "The Social Netwrok Inbox"
year : "2020"
